### ISSUE TITLE
Waits for user interaction while Solr install script

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/solr.deb#1]
On Ubuntu the original Solr install script waits for user interaction to quit a status message by enter "q".

So Solr can not be installed unattendent or within a GUI package manager yet.

Until a fix is found you have to use
apt install ./open-semantic-search-server-ubuntu_*.deb
and after a while enter q manually.

Someone knows how to set shell environment temporary in postinst script not to use such a print tool which needs interaction?

If not, maybe writing q to stdin in postinst script as workarround...

**Comment by Mandalka** [comment]
On new Debian 9 Strech it's the same.

**Comment by Mandalka** [comment]
Can be disable to wait for user input by setting
SYSTEMD_PAGER=""
or delete "service solr status" call from install_solr_service.sh

**Comment by sarnobat** [comment]
Neither of those 2 workarounds does anything for me.

**Comment by Mandalka** [comment]
setting the variable has to be done by the export command
export SYSTEMD_PAGER=""

I'll add it to the Debian package so issue can be closed.

**Comment by Mandalka** [comment]
Added by https://github.com/opensemanticsearch/solr.deb/commit/976cf778d6c57d74b7f2586c73ce750db3d3079e
