### ISSUE TITLE
Upgrade to Solr 7

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/solr.deb#3]

**Comment by hillar** [comment]
+1

**Comment by Mandalka** [comment]
Solr field config of named entity dictionaries now done by Solr REST API by the new Open Semantic Entity Search API component dictionary manager.

**Comment by Mandalka** [comment]
Upgraded Solr Server installation/configuration to Solr 7.3.0.

Todo: Upgrade schema

**Comment by Mandalka** [comment]
Preconfigured managed schema for Solr 7 with managed synonyms by REST-API.
