### ISSUE TITLE
Build question

### ISSUE THREAD

**Issue by Quyrean** [opensemanticsearch/solr.deb#4]
> Add solr-7.x.x.tgz archive from http://lucene.apache.org/solr to the directory usr/src

Do I just put the tar file in the directory or do I need to untar it first?

PS: thanks for the checkin last night, I was getting errors trying to build this package yesterday and now it is working.

**Comment by opensemanticsearch** [comment]
Added to readme:

Add the solr-7.x.x.tgz archive (the Solr installer needs the archive file, so do not extract!) from http://lucene.apache.org/solr to the (sub)directory ./usr/src (since git does not store empty directories yet not existent)
