### ISSUE TITLE
Upgrade to Solr 8

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/solr.deb#7]

**Comment by StudyExchange** [comment]
Can not write data into Solr, this docker container has issue: "max.booleanClauses"

**Comment by Mandalka** [comment]
Upgraded binaries of deb package by https://github.com/opensemanticsearch/solr.deb/commit/35134545a03f9de142ed161b066087025422f0c7 and https://github.com/opensemanticsearch/open-semantic-search/commit/890f53302a43753a234dadfd3d081faf98986675

**Comment by Mandalka** [comment]
Migrated solrconfig.xml by https://github.com/opensemanticsearch/solr.deb/commit/58ca9aaa8bf5bec548a1ef924fe8af531086eac3 and https://github.com/opensemanticsearch/solr.deb/commit/713a3d45c62b93913efd0583af39b94817f13e85

**Comment by Mandalka** [comment]
Upgraded solr.in.sh by https://github.com/opensemanticsearch/solr.deb/commit/165fd48b77f00080da3c5ce97a819d1d9190c56b
