### ISSUE TITLE
Docker: Use standard directory /var/solr

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/solr.deb#8]
Use /var/solr for preconfigured schemas (currently in /opt) and index for using standard paths for persistence of index used by [Solr-Docker](https://github.com/docker-solr/docker-solr) and https://github.com/opensemanticsearch/open-semantic-search/blob/master/docker-compose.yml

**Comment by Mandalka** [comment]
Done by upgrade to Solr 8 which the official Docker release now uses the standard directory /var/solr
